### ISSUE TITLE
Code crash

### ISSUE THREAD

**Issue by Sugz** [d0sboots/dyson-sphere-program#2]
Hello, I'm pretty much getting the same result as with the previous issue:
```
Reading data... Traceback (most recent call last):
  File "D:\...\dyson_wiki.py", line 632, in <module>
    main()
  File "D:\...\dyson_wiki.py", line 597, in main
    data = dysonsphere.load_all()
  File "D:\...\dysonsphere.py", line 535, in load_all
    result = dict((x, load_data(x, path.join(root_dir, x + '.dat')))
  File "D:\...\dysonsphere.py", line 535, in <genexpr>
    result = dict((x, load_data(x, path.join(root_dir, x + '.dat')))
  File "D:\...\dysonsphere.py", line 522, in load_data
    return cls(*reader.get_funcs())
  File "<dynamic StringProtoSet code>", line 17, in __init__
  File "<dynamic StringProtoSet code>", line 17, in <listcomp>
  File "<dynamic StringProto code>", line 13, in __init__
ValueError: read length must be non-negative or -1
```

I'm wondering about a two things though:
 - I extracted ItemProtoSet.dat, RecipeProtoSet.dat, StringProtoSet.dat, TechProtoSet.dat using UABE, but they are only 80 bytes, MonoScript instead of MonoBehavior and do not match the Path IDs you indicated in dysonsphere.py.
    ![ItemProtoSet](https://user-images.githubusercontent.com/15956915/151645999-17856594-2400-4db0-86ea-e418d2bd3de2.png)
 - I'm using python 3.10, this may be an issue ?

**Comment by d0sboots** [comment]
Ah, the first part is your issue. You need to get the MonoBehavior, not the MonoScript of the same name. The MonoBehavior for ItemProtoSet is FileID 0, PathID 33829 with size 26884 (for the current version of the game).

To find them with UABE, I search for "*ProtoSet" starting from the beginning, that gets to the start of the MonoBehavior block.

**Comment by Sugz** [comment]
Ahhhh my bad... Works like a charm :D
Thanks for your help.
