### ISSUE TITLE
Requesting an update to the Fandom data

### ISSUE THREAD

**Issue by cssinate** [d0sboots/dyson-sphere-program#4]
Hi there! As of September 2022, there's now a Logistics Distributor and Logistics Bot that goes with it. I play DSP on GeForce Now, and don't have the Unity tools to do the ripping myself right now.

If you're able to do the update, that would be awesome. If you're not, please say so, and I'll spend the time getting all that tooling set up to do it on my own.

Thanks!

**Comment by d0sboots** [comment]
Thanks for the heads-up. I've stepped away from the game, so I pretty much ignore the wiki these days unless poked.

I've updated the data, but there's new icons and pages that are needed. I'll try to get around to ripping and adding them, but I might fail at that.

**Comment by d0sboots** [comment]
OK, I have uploaded all images and created all missing pages (including a number that were missing from before this latest updated).
